### ISSUE TITLE
Error: cannot find module 'espree' when trying to run cli

### ISSUE THREAD

**Issue by Bobakanoosh** [batijs/bati#104]
When I run `pnpm create @batijs/app`, I get:
```
node:internal/modules/cjs/loader:995
  const err = new Error(message);
              ^

Error: Cannot find module 'espree'
Require stack:
- C:\Users\user\AppData\Local\pnpm\store\v3\tmp\dlx-20084\node_modules\.pnpm\@batijs+core@0.0.99\node_modules\@batijs\core\dist\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at file:///C:/Users/user/AppData/Local/pnpm/store/v3/tmp/dlx-20084/node_modules/.pnpm/@batijs+core@0.0.99/node_modules/@batijs/core/dist/index.js:160:956
    at file:///C:/Users/user/AppData/Local/pnpm/store/v3/tmp/dlx-20084/node_modules/.pnpm/@batijs+core@0.0.99/node_modules/@batijs/core/dist/index.js:9:595
    at file:///C:/Users/user/AppData/Local/pnpm/store/v3/tmp/dlx-20084/node_modules/.pnpm/@batijs+core@0.0.99/node_modules/@batijs/core/dist/index.js:163:6059
    at file:///C:/Users/user/AppData/Local/pnpm/store/v3/tmp/dlx-20084/node_modules/.pnpm/@batijs+core@0.0.99/node_modules/@batijs/core/dist/index.js:9:595
    at file:///C:/Users/user/AppData/Local/pnpm/store/v3/tmp/dlx-20084/node_modules/.pnpm/@batijs+core@0.0.99/node_modules/@batijs/core/dist/index.js:163:6161
    at file:///C:/Users/user/AppData/Local/pnpm/store/v3/tmp/dlx-20084/node_modules/.pnpm/@batijs+core@0.0.99/node_modules/@batijs/core/dist/index.js:9:595
    at file:///C:/Users/user/AppData/Local/pnpm/store/v3/tmp/dlx-20084/node_modules/.pnpm/@batijs+core@0.0.99/node_modules/@batijs/core/dist/index.js:1062:2023
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\AppData\\Local\\pnpm\\store\\v3\\tmp\\dlx-20084\\node_modules\\.pnpm\\@batijs+core@0.0.99\\node_modules\\@batijs\\core\\dist\\index.js'
  ]
}
```

Node version: v18.12.1
Npm version: 8.19.2

**Comment by magne4000** [comment]
You can use `pnpm create @batijs/app@0.0.94` which is the latest working version it seems.
I'm on a fix

**Comment by magne4000** [comment]
Last stable version should fix the issue!

**Comment by Bobakanoosh** [comment]
Awesome thank you
