### ISSUE TITLE
Website: show a message for features incompatible with stackblitz

### ISSUE THREAD

**Issue by JosXa** [batijs/bati#290]
**Describe the bug**

On Stackblitz from https://batijs.dev:

```
~/projects/p8kcpu--run
❯ pnpm run dev

> my-app@0.0.1 dev /home/projects/p8kcpu--run
> vite

failed to load config from /home/projects/p8kcpu--run/vite.config.ts
error when starting dev server:
Error: Could not locate the bindings file. Tried:
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/build/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/compiled/18.20.3/linux/x64/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /home/projects/p8kcpu--run/node_modules/.pnpm/better-sqlite3@11.1.2/node_modules/better-sqlite3/lib/binding/node-v108-linux-x64/better_sqlite3.node
    at resolveConfig (file:///home/projects/p8kcpu--run/node_modules/.pnpm/vite@5.3.3_@types+node@18.19.39/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66484:24)
    at _createServer (file:///home/projects/p8kcpu--run/node_modules/.pnpm/vite@5.3.3_@types+node@18.19.39/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:63097:18)
    at CAC.eval (file:///home/projects/p8kcpu--run/node_modules/.pnpm/vite@5.3.3_@types+node@18.19.39/node_modules/vite/dist/node/cli.js:750:20)
 ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**
![image](https://github.com/batijs/bati/assets/7313176/5941c287-9ce6-4459-9c68-52ae9e9fa93b)

`pnpm create @batijs/app --solid --tailwindcss --auth0 --trpc --hono --drizzle --cloudflare --biome`

--> Try on Stackblitz

**Expected behavior**
Working setup

**Comment by magne4000** [comment]
`better-sqlite3` doesn't work on Stackblitz, it's a known limitation.
The web interface should account for that though.

**Comment by JosXa** [comment]
I see. Yeah I guess a warning would be nice. Suppose that's drizzle's fault?

**Comment by magne4000** [comment]
> Suppose that's drizzle's fault?
Yup
